
loglevel:
  controllers: TRACE
  services: INFO

customer-service:
  serviceId: access-mysql-service
  host: localhost
  port: 8080

order-service:
  serviceId: order-service
  host: localhost
  port: 8083
